on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'ubuntu-20.04', 'macos-11', 'macos-14']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile easy_changelog.py --name easy-changelog-${{ matrix.os }}
    - run: ./dist/easy-changelog-${{ matrix.os }} -h
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: easy-changelog-${{ matrix.os }}
        
  build-alpine:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: addnab/docker-run-action@v3
      with:
        image: six8/pyinstaller-alpine:alpine-3.6-pyinstaller-v3.4
        options: -v ${{ github.workspace }}:/src
        run: |
          /pyinstaller/pyinstaller.sh \
          --noconfirm \
          --onefile \
          --log-level DEBUG \
          --clean \
          --name easy-changelog-alpine \
          easy_changelog.py
    - run: ${{ github.workspace }}/dist/easy-changelog-alpine -h
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/dist/*
        name: easy-changelog-alpine

  build-shiv:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: pip install -r requirements.txt shiv
    - run: mkdir ./dist
    - run: shiv -e easy_changelog:main -o ./dist/easy-changelog-shiv packaging
    - run: tree
#    - run: ./dist/easy-changelog-shiv -h
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: easy-changelog-shiv
