on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-2019', 'ubuntu-20.04', 'macos-11', 'macos-14']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile easy_changelog.py --name easy-changelog-${{ matrix.os }}
    - run: ./dist/easy_changelog-${{ matrix.os }} -h
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
